version: "3.9"

services:
  api:
    build: .
    container_name: artwork_api
    ports:
      -"8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: go run ./cmd/server
  
  db: 
    image: postgres:16-alpine
    container_name: artwork_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: